// <auto-generated />
using System;
using BelicosaApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BelicosaApi.Migrations
{
    [DbContext(typeof(BelicosaApiContext))]
    [Migration("20240205064852_AddAvailableColorsFieldToBelicosaGame")]
    partial class AddAvailableColorsFieldToBelicosaGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BelicosaApi.Models.BelicosaGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int[]>("AvailableColors")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("CardExchangeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BelicosaApi.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Continent");
                });

            modelBuilder.Entity("BelicosaApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmyColor")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableFreeDistributionTroops")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BelicosaApi.Models.Territory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContinentId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OccupyingPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("TerritoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TroopCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.HasIndex("GameId");

                    b.HasIndex("OccupyingPlayerId");

                    b.HasIndex("TerritoryId");

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("BelicosaApi.Models.TerritoryCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("HolderId")
                        .HasColumnType("integer");

                    b.Property<int>("Shape")
                        .HasColumnType("integer");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("HolderId");

                    b.HasIndex("TerritoryId");

                    b.ToTable("TerritoryCard");
                });

            modelBuilder.Entity("BelicosaApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BelicosaApi.Models.BelicosaGame", b =>
                {
                    b.HasOne("BelicosaApi.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BelicosaApi.Models.Continent", b =>
                {
                    b.HasOne("BelicosaApi.Models.BelicosaGame", "Game")
                        .WithMany("Continents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BelicosaApi.Models.Player", b =>
                {
                    b.HasOne("BelicosaApi.Models.BelicosaGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelicosaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BelicosaApi.Models.Territory", b =>
                {
                    b.HasOne("BelicosaApi.Models.Continent", null)
                        .WithMany("Territories")
                        .HasForeignKey("ContinentId");

                    b.HasOne("BelicosaApi.Models.BelicosaGame", "Game")
                        .WithMany("Territories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelicosaApi.Models.Player", "OccupyingPlayer")
                        .WithMany()
                        .HasForeignKey("OccupyingPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelicosaApi.Models.Territory", null)
                        .WithMany("BorderTerritories")
                        .HasForeignKey("TerritoryId");

                    b.Navigation("Game");

                    b.Navigation("OccupyingPlayer");
                });

            modelBuilder.Entity("BelicosaApi.Models.TerritoryCard", b =>
                {
                    b.HasOne("BelicosaApi.Models.BelicosaGame", "Game")
                        .WithMany("TerritoryCards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelicosaApi.Models.Player", "Holder")
                        .WithMany()
                        .HasForeignKey("HolderId");

                    b.HasOne("BelicosaApi.Models.Territory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Holder");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("BelicosaApi.Models.BelicosaGame", b =>
                {
                    b.Navigation("Continents");

                    b.Navigation("Players");

                    b.Navigation("Territories");

                    b.Navigation("TerritoryCards");
                });

            modelBuilder.Entity("BelicosaApi.Models.Continent", b =>
                {
                    b.Navigation("Territories");
                });

            modelBuilder.Entity("BelicosaApi.Models.Territory", b =>
                {
                    b.Navigation("BorderTerritories");
                });
#pragma warning restore 612, 618
        }
    }
}
